### ISSUE TITLE
Something about bert-for-coqa

### ISSUE THREAD

**Issue by jaytsien** [hquzhuguofeng/Bert-for-coqa#1]
能加个联系方式吗？

**Comment by hquzhuguofeng** [comment]
492070779@qq.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jaytsien"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 晚上7:39
收件人:&nbsp;"hquzhuguofeng/Bert-for-coqa"<Bert-for-coqa@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hquzhuguofeng/Bert-for-coqa] Something about bert-for-coqa (#1)




能加个联系方式吗？
